# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Configs.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Configs(object):
    def setupUi(self, Configs):
        Configs.setObjectName("Configs")
        Configs.resize(529, 554)
        self.PBCerrar = QtWidgets.QPushButton(Configs)
        self.PBCerrar.setGeometry(QtCore.QRect(340, 510, 171, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBCerrar.setFont(font)
        self.PBCerrar.setObjectName("PBCerrar")
        self.PBGuardar = QtWidgets.QPushButton(Configs)
        self.PBGuardar.setGeometry(QtCore.QRect(140, 510, 171, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBGuardar.setFont(font)
        self.PBGuardar.setObjectName("PBGuardar")
        self.groupBox = QtWidgets.QGroupBox(Configs)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 451, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.RutaCampo = QtWidgets.QLineEdit(self.groupBox)
        self.RutaCampo.setGeometry(QtCore.QRect(90, 30, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RutaCampo.setFont(font)
        self.RutaCampo.setText("")
        self.RutaCampo.setObjectName("RutaCampo")
        self.RutaLbl = QtWidgets.QLabel(self.groupBox)
        self.RutaLbl.setGeometry(QtCore.QRect(11, 30, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RutaLbl.setFont(font)
        self.RutaLbl.setObjectName("RutaLbl")
        self.RepClieCampo = QtWidgets.QLineEdit(self.groupBox)
        self.RepClieCampo.setGeometry(QtCore.QRect(140, 60, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RepClieCampo.setFont(font)
        self.RepClieCampo.setText("")
        self.RepClieCampo.setObjectName("RepClieCampo")
        self.RepClieLb = QtWidgets.QLabel(self.groupBox)
        self.RepClieLb.setGeometry(QtCore.QRect(10, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RepClieLb.setFont(font)
        self.RepClieLb.setObjectName("RepClieLb")
        self.OrdSurtidoCampo = QtWidgets.QLineEdit(self.groupBox)
        self.OrdSurtidoCampo.setGeometry(QtCore.QRect(140, 90, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.OrdSurtidoCampo.setFont(font)
        self.OrdSurtidoCampo.setText("")
        self.OrdSurtidoCampo.setObjectName("OrdSurtidoCampo")
        self.OSurtLbl = QtWidgets.QLabel(self.groupBox)
        self.OSurtLbl.setGeometry(QtCore.QRect(10, 90, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OSurtLbl.setFont(font)
        self.OSurtLbl.setObjectName("OSurtLbl")

        self.retranslateUi(Configs)
        QtCore.QMetaObject.connectSlotsByName(Configs)

    def retranslateUi(self, Configs):
        _translate = QtCore.QCoreApplication.translate
        Configs.setWindowTitle(_translate("Configs", "Configuraciones"))
        self.PBCerrar.setText(_translate("Configs", "Cerrar"))
        self.PBGuardar.setText(_translate("Configs", "Guardar "))
        self.groupBox.setTitle(_translate("Configs", "Rutas:"))
        self.RutaCampo.setPlaceholderText(_translate("Configs", "Ruta de USB para Bajar y subir info para tolva"))
        self.RutaLbl.setText(_translate("Configs", " USB:"))
        self.RepClieCampo.setPlaceholderText(_translate("Configs", "Ruta donde se colocaran los reportes de clientes"))
        self.RepClieLb.setText(_translate("Configs", "Reporte Clientes:"))
        self.OrdSurtidoCampo.setPlaceholderText(_translate("Configs", "Ruta donde se guardaran el log de todos los surtidos"))
        self.OSurtLbl.setText(_translate("Configs", "Ordenes Surtido:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Configs = QtWidgets.QDialog()
    ui = Ui_Configs()
    ui.setupUi(Configs)
    Configs.show()
    sys.exit(app.exec_())
