# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Corrales.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UiCorrales(object):
    def setupUi(self, UiCorrales):
        UiCorrales.setObjectName("UiCorrales")
        UiCorrales.resize(584, 795)
        UiCorrales.setLayoutDirection(QtCore.Qt.LeftToRight)
        UiCorrales.setStyleSheet("DialogAltaAnimales{\n"
"\n"
"}\n"
"\n"
"lineEdit{  font-size: 16px;\n"
"\n"
"}")
        self.groupBox = QtWidgets.QGroupBox(UiCorrales)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 401, 121))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.ClaveLbl = QtWidgets.QLabel(self.groupBox)
        self.ClaveLbl.setGeometry(QtCore.QRect(10, 33, 44, 19))
        self.ClaveLbl.setStyleSheet("QLabel {\n"
"font-size: 16px;\n"
"\n"
"}")
        self.ClaveLbl.setObjectName("ClaveLbl")
        self.ClaveCampo = QtWidgets.QLineEdit(self.groupBox)
        self.ClaveCampo.setGeometry(QtCore.QRect(94, 33, 133, 20))
        self.ClaveCampo.setText("")
        self.ClaveCampo.setObjectName("ClaveCampo")
        self.NombreLbl = QtWidgets.QLabel(self.groupBox)
        self.NombreLbl.setGeometry(QtCore.QRect(10, 59, 63, 19))
        self.NombreLbl.setStyleSheet("QLabel {\n"
"font-size: 16px;\n"
"\n"
"}")
        self.NombreLbl.setObjectName("NombreLbl")
        self.NombreCampo = QtWidgets.QLineEdit(self.groupBox)
        self.NombreCampo.setGeometry(QtCore.QRect(94, 59, 133, 20))
        self.NombreCampo.setText("")
        self.NombreCampo.setObjectName("NombreCampo")
        self.DireccionLbl = QtWidgets.QLabel(self.groupBox)
        self.DireccionLbl.setGeometry(QtCore.QRect(10, 85, 78, 19))
        self.DireccionLbl.setStyleSheet("QLabel {\n"
"font-size: 16px;\n"
"\n"
"}")
        self.DireccionLbl.setObjectName("DireccionLbl")
        self.CapaCampo = QtWidgets.QLineEdit(self.groupBox)
        self.CapaCampo.setGeometry(QtCore.QRect(94, 85, 133, 20))
        self.CapaCampo.setText("")
        self.CapaCampo.setObjectName("CapaCampo")
        self.MenBox_2 = QtWidgets.QGroupBox(UiCorrales)
        self.MenBox_2.setGeometry(QtCore.QRect(50, 710, 351, 51))
        self.MenBox_2.setObjectName("MenBox_2")
        self.MessageLbl_2 = QtWidgets.QLabel(self.MenBox_2)
        self.MessageLbl_2.setGeometry(QtCore.QRect(10, 20, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MessageLbl_2.setFont(font)
        self.MessageLbl_2.setStyleSheet("MessageLbl {\n"
"font-color: rgb(0, 0, 255);\n"
"}")
        self.MessageLbl_2.setObjectName("MessageLbl_2")
        self.Tabla = QtWidgets.QTableView(UiCorrales)
        self.Tabla.setGeometry(QtCore.QRect(30, 160, 391, 501))
        self.Tabla.setObjectName("Tabla")
        self.PBBorrar = QtWidgets.QPushButton(UiCorrales)
        self.PBBorrar.setGeometry(QtCore.QRect(300, 800, 75, 23))
        self.PBBorrar.setObjectName("PBBorrar")
        self.PBCerrar = QtWidgets.QPushButton(UiCorrales)
        self.PBCerrar.setGeometry(QtCore.QRect(300, 830, 75, 23))
        self.PBCerrar.setObjectName("PBCerrar")
        self.layoutWidget = QtWidgets.QWidget(UiCorrales)
        self.layoutWidget.setGeometry(QtCore.QRect(450, 180, 121, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PBActualizar = QtWidgets.QPushButton(self.layoutWidget)
        self.PBActualizar.setObjectName("PBActualizar")
        self.verticalLayout.addWidget(self.PBActualizar)
        self.PBCancelar = QtWidgets.QPushButton(self.layoutWidget)
        self.PBCancelar.setObjectName("PBCancelar")
        self.verticalLayout.addWidget(self.PBCancelar)
        self.PBAgregar = QtWidgets.QPushButton(self.layoutWidget)
        self.PBAgregar.setObjectName("PBAgregar")
        self.verticalLayout.addWidget(self.PBAgregar)
        self.PBBorrar_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.PBBorrar_2.setObjectName("PBBorrar_2")
        self.verticalLayout.addWidget(self.PBBorrar_2)
        self.PBCerrar_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.PBCerrar_2.setObjectName("PBCerrar_2")
        self.verticalLayout.addWidget(self.PBCerrar_2)

        self.retranslateUi(UiCorrales)
        QtCore.QMetaObject.connectSlotsByName(UiCorrales)

    def retranslateUi(self, UiCorrales):
        _translate = QtCore.QCoreApplication.translate
        UiCorrales.setWindowTitle(_translate("UiCorrales", "Catalogo de Corrales"))
        self.groupBox.setTitle(_translate("UiCorrales", "Corral:"))
        self.ClaveLbl.setText(_translate("UiCorrales", "Clave:"))
        self.NombreLbl.setText(_translate("UiCorrales", "Nombre:"))
        self.DireccionLbl.setText(_translate("UiCorrales", "Capacidad:"))
        self.MenBox_2.setTitle(_translate("UiCorrales", "Mensajes"))
        self.MessageLbl_2.setText(_translate("UiCorrales", "TextLabel"))
        self.PBBorrar.setText(_translate("UiCorrales", "Borrar"))
        self.PBCerrar.setText(_translate("UiCorrales", "Cerrar"))
        self.PBActualizar.setText(_translate("UiCorrales", "Actualizar"))
        self.PBCancelar.setText(_translate("UiCorrales", "Cancelar"))
        self.PBAgregar.setText(_translate("UiCorrales", "Agregar"))
        self.PBBorrar_2.setText(_translate("UiCorrales", "Borrar"))
        self.PBCerrar_2.setText(_translate("UiCorrales", "Cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UiCorrales = QtWidgets.QDialog()
    ui = Ui_UiCorrales()
    ui.setupUi(UiCorrales)
    UiCorrales.show()
    sys.exit(app.exec_())
