# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ListaUltimoInINicMP.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListaUltimoInvMP(object):
    def setupUi(self, ListaUltimoInvMP):
        ListaUltimoInvMP.setObjectName("ListaUltimoInvMP")
        ListaUltimoInvMP.resize(688, 709)
        self.PBCerrar = QtWidgets.QPushButton(ListaUltimoInvMP)
        self.PBCerrar.setGeometry(QtCore.QRect(180, 670, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBCerrar.setFont(font)
        self.PBCerrar.setObjectName("PBCerrar")
        self.Tabla = QtWidgets.QTableWidget(ListaUltimoInvMP)
        self.Tabla.setGeometry(QtCore.QRect(20, 50, 631, 611))
        self.Tabla.setObjectName("Tabla")
        self.Tabla.setColumnCount(5)
        self.Tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.Tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.Tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.Tabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.Tabla.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(4, item)
        self.PBImprimir = QtWidgets.QPushButton(ListaUltimoInvMP)
        self.PBImprimir.setGeometry(QtCore.QRect(20, 670, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBImprimir.setFont(font)
        self.PBImprimir.setObjectName("PBImprimir")
        self.BanLbl_3 = QtWidgets.QLabel(ListaUltimoInvMP)
        self.BanLbl_3.setGeometry(QtCore.QRect(20, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.BanLbl_3.setFont(font)
        self.BanLbl_3.setAlignment(QtCore.Qt.AlignCenter)
        self.BanLbl_3.setObjectName("BanLbl_3")

        self.retranslateUi(ListaUltimoInvMP)
        QtCore.QMetaObject.connectSlotsByName(ListaUltimoInvMP)

    def retranslateUi(self, ListaUltimoInvMP):
        _translate = QtCore.QCoreApplication.translate
        ListaUltimoInvMP.setWindowTitle(_translate("ListaUltimoInvMP", "Reporte  Materia Prima por Almacen"))
        self.PBCerrar.setText(_translate("ListaUltimoInvMP", "Cerrar"))
        item = self.Tabla.horizontalHeaderItem(0)
        item.setText(_translate("ListaUltimoInvMP", "Almacen"))
        item = self.Tabla.horizontalHeaderItem(1)
        item.setText(_translate("ListaUltimoInvMP", "Materia Prima"))
        item = self.Tabla.horizontalHeaderItem(2)
        item.setText(_translate("ListaUltimoInvMP", "Fecha"))
        item = self.Tabla.horizontalHeaderItem(3)
        item.setText(_translate("ListaUltimoInvMP", "Cantidad"))
        self.PBImprimir.setText(_translate("ListaUltimoInvMP", "Imprimir"))
        self.BanLbl_3.setText(_translate("ListaUltimoInvMP", "Ultimo Inventario Por Alamacen y MP"))
