# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogRec.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogRecv(object):
    def setupUi(self, LogRecv):
        LogRecv.setObjectName("LogRecv")
        LogRecv.resize(634, 386)
        self.RecTextEdit = QtWidgets.QTextEdit(LogRecv)
        self.RecTextEdit.setGeometry(QtCore.QRect(30, 90, 571, 231))
        self.RecTextEdit.setObjectName("RecTextEdit")
        self.PBEnviar = QtWidgets.QPushButton(LogRecv)
        self.PBEnviar.setGeometry(QtCore.QRect(410, 340, 75, 23))
        self.PBEnviar.setObjectName("PBEnviar")
        self.PBParar = QtWidgets.QPushButton(LogRecv)
        self.PBParar.setGeometry(QtCore.QRect(280, 340, 75, 23))
        self.PBParar.setObjectName("PBParar")

        self.retranslateUi(LogRecv)
        QtCore.QMetaObject.connectSlotsByName(LogRecv)

    def retranslateUi(self, LogRecv):
        _translate = QtCore.QCoreApplication.translate
        LogRecv.setWindowTitle(_translate("LogRecv", "Log de Recepcion de Servidos"))
        self.PBEnviar.setText(_translate("LogRecv", "Enviar"))
        self.PBParar.setText(_translate("LogRecv", "Parar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogRecv = QtWidgets.QDialog()
    ui = Ui_LogRecv()
    ui.setupUi(LogRecv)
    LogRecv.show()
    sys.exit(app.exec_())
