# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MateriasPrimas.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogoMatPrimas(object):
    def setupUi(self, DialogoMatPrimas):
        DialogoMatPrimas.setObjectName("DialogoMatPrimas")
        DialogoMatPrimas.resize(575, 626)
        DialogoMatPrimas.setStyleSheet("DialogAltaAnimales{\n"
"\n"
"}\n"
"\n"
"lineEdit{  font-size: 16px;\n"
"\n"
"}")
        self.ClaveLbl = QtWidgets.QLabel(DialogoMatPrimas)
        self.ClaveLbl.setGeometry(QtCore.QRect(9, 9, 44, 19))
        self.ClaveLbl.setStyleSheet("QLabel {\n"
"font-size: 14px;\n"
"\n"
"}")
        self.ClaveLbl.setObjectName("ClaveLbl")
        self.ClaveCampo = QtWidgets.QLineEdit(DialogoMatPrimas)
        self.ClaveCampo.setGeometry(QtCore.QRect(50, 10, 91, 20))
        self.ClaveCampo.setText("")
        self.ClaveCampo.setObjectName("ClaveCampo")
        self.NombreLbl = QtWidgets.QLabel(DialogoMatPrimas)
        self.NombreLbl.setGeometry(QtCore.QRect(10, 40, 87, 19))
        self.NombreLbl.setStyleSheet("QLabel {\n"
"font-size: 14px;\n"
"\n"
"}")
        self.NombreLbl.setObjectName("NombreLbl")
        self.DescripcionCampo = QtWidgets.QLineEdit(DialogoMatPrimas)
        self.DescripcionCampo.setGeometry(QtCore.QRect(100, 40, 221, 20))
        self.DescripcionCampo.setText("")
        self.DescripcionCampo.setObjectName("DescripcionCampo")
        self.DireccionLbl = QtWidgets.QLabel(DialogoMatPrimas)
        self.DireccionLbl.setGeometry(QtCore.QRect(160, 10, 121, 19))
        self.DireccionLbl.setStyleSheet("QLabel {\n"
"font-size: 14px;\n"
"\n"
"}")
        self.DireccionLbl.setObjectName("DireccionLbl")
        self.PUCampo = QtWidgets.QLineEdit(DialogoMatPrimas)
        self.PUCampo.setGeometry(QtCore.QRect(260, 10, 101, 20))
        self.PUCampo.setText("")
        self.PUCampo.setObjectName("PUCampo")
        self.Tabla = QtWidgets.QTreeWidget(DialogoMatPrimas)
        self.Tabla.setGeometry(QtCore.QRect(10, 70, 551, 441))
        self.Tabla.setObjectName("Tabla")
        self.Tabla.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.Tabla.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        self.Tabla.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        self.Tabla.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        self.GuardarBot = QtWidgets.QPushButton(DialogoMatPrimas)
        self.GuardarBot.setGeometry(QtCore.QRect(250, 540, 75, 23))
        self.GuardarBot.setObjectName("GuardarBot")
        self.NuevoBot = QtWidgets.QPushButton(DialogoMatPrimas)
        self.NuevoBot.setGeometry(QtCore.QRect(330, 540, 75, 23))
        self.NuevoBot.setObjectName("NuevoBot")
        self.EliminarBot = QtWidgets.QPushButton(DialogoMatPrimas)
        self.EliminarBot.setGeometry(QtCore.QRect(410, 540, 75, 23))
        self.EliminarBot.setObjectName("EliminarBot")
        self.CerrarBot = QtWidgets.QPushButton(DialogoMatPrimas)
        self.CerrarBot.setGeometry(QtCore.QRect(649, 594, 75, 23))
        self.CerrarBot.setObjectName("CerrarBot")
        self.NombreLbl_2 = QtWidgets.QLabel(DialogoMatPrimas)
        self.NombreLbl_2.setGeometry(QtCore.QRect(370, 10, 87, 19))
        self.NombreLbl_2.setStyleSheet("QLabel {\n"
"font-size: 14px;\n"
"\n"
"}")
        self.NombreLbl_2.setObjectName("NombreLbl_2")
        self.CerrarBot_2 = QtWidgets.QPushButton(DialogoMatPrimas)
        self.CerrarBot_2.setGeometry(QtCore.QRect(490, 540, 75, 23))
        self.CerrarBot_2.setObjectName("CerrarBot_2")
        self.UdeMComBox = QtWidgets.QComboBox(DialogoMatPrimas)
        self.UdeMComBox.setGeometry(QtCore.QRect(440, 10, 81, 22))
        self.UdeMComBox.setObjectName("UdeMComBox")
        self.MenBox = QtWidgets.QGroupBox(DialogoMatPrimas)
        self.MenBox.setGeometry(QtCore.QRect(10, 520, 231, 51))
        self.MenBox.setObjectName("MenBox")
        self.MessageLbl = QtWidgets.QLabel(self.MenBox)
        self.MessageLbl.setGeometry(QtCore.QRect(10, 20, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MessageLbl.setFont(font)
        self.MessageLbl.setStyleSheet("MessageLbl {\n"
"font-color: rgb(0, 0, 255);\n"
"}")
        self.MessageLbl.setObjectName("MessageLbl")

        self.retranslateUi(DialogoMatPrimas)
        QtCore.QMetaObject.connectSlotsByName(DialogoMatPrimas)

    def retranslateUi(self, DialogoMatPrimas):
        _translate = QtCore.QCoreApplication.translate
        DialogoMatPrimas.setWindowTitle(_translate("DialogoMatPrimas", "Catalogo Materias Primas"))
        self.ClaveLbl.setText(_translate("DialogoMatPrimas", "Clave:"))
        self.NombreLbl.setText(_translate("DialogoMatPrimas", "Descripcion:"))
        self.DireccionLbl.setText(_translate("DialogoMatPrimas", "Precio Unitario:"))
        self.Tabla.headerItem().setText(0, _translate("DialogoMatPrimas", "Clave"))
        self.Tabla.headerItem().setText(1, _translate("DialogoMatPrimas", "Nombre"))
        self.Tabla.headerItem().setText(2, _translate("DialogoMatPrimas", "UnidadMedida"))
        self.Tabla.headerItem().setText(3, _translate("DialogoMatPrimas", "Precio Unitario"))
        self.GuardarBot.setText(_translate("DialogoMatPrimas", "Guardar"))
        self.NuevoBot.setText(_translate("DialogoMatPrimas", "Editar"))
        self.EliminarBot.setText(_translate("DialogoMatPrimas", "Eliminar"))
        self.CerrarBot.setText(_translate("DialogoMatPrimas", "Cerrar"))
        self.NombreLbl_2.setText(_translate("DialogoMatPrimas", "U de M:"))
        self.CerrarBot_2.setText(_translate("DialogoMatPrimas", "Cerrar"))
        self.MenBox.setTitle(_translate("DialogoMatPrimas", "Mensajes"))
        self.MessageLbl.setText(_translate("DialogoMatPrimas", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogoMatPrimas = QtWidgets.QDialog()
    ui = Ui_DialogoMatPrimas()
    ui.setupUi(DialogoMatPrimas)
    DialogoMatPrimas.show()
    sys.exit(app.exec_())
