# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MvtoAnimalesPpal.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MovAnimalesPpal(object):
    def setupUi(self, MovAnimalesPpal):
        MovAnimalesPpal.setObjectName("MovAnimalesPpal")
        MovAnimalesPpal.resize(844, 640)
        self.Tabla = QtWidgets.QTableWidget(MovAnimalesPpal)
        self.Tabla.setGeometry(QtCore.QRect(10, 20, 811, 541))
        self.Tabla.setObjectName("Tabla")
        self.Tabla.setColumnCount(7)
        self.Tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(6, item)
        self.PBCerrar = QtWidgets.QPushButton(MovAnimalesPpal)
        self.PBCerrar.setGeometry(QtCore.QRect(720, 590, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBCerrar.setFont(font)
        self.PBCerrar.setObjectName("PBCerrar")
        self.PBAgregar = QtWidgets.QPushButton(MovAnimalesPpal)
        self.PBAgregar.setGeometry(QtCore.QRect(570, 590, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBAgregar.setFont(font)
        self.PBAgregar.setObjectName("PBAgregar")
        self.groupBox_2 = QtWidgets.QGroupBox(MovAnimalesPpal)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 570, 181, 53))
        self.groupBox_2.setObjectName("groupBox_2")
        self.RBotUlt100 = QtWidgets.QRadioButton(self.groupBox_2)
        self.RBotUlt100.setGeometry(QtCore.QRect(10, 23, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBotUlt100.setFont(font)
        self.RBotUlt100.setAcceptDrops(False)
        self.RBotUlt100.setChecked(True)
        self.RBotUlt100.setObjectName("RBotUlt100")
        self.RBotTodos = QtWidgets.QRadioButton(self.groupBox_2)
        self.RBotTodos.setGeometry(QtCore.QRect(109, 23, 58, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBotTodos.setFont(font)
        self.RBotTodos.setObjectName("RBotTodos")
        self.PBActualizar = QtWidgets.QPushButton(MovAnimalesPpal)
        self.PBActualizar.setGeometry(QtCore.QRect(430, 590, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBActualizar.setFont(font)
        self.PBActualizar.setObjectName("PBActualizar")
        self.PBEditar = QtWidgets.QPushButton(MovAnimalesPpal)
        self.PBEditar.setGeometry(QtCore.QRect(250, 580, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBEditar.setFont(font)
        self.PBEditar.setObjectName("PBEditar")

        self.retranslateUi(MovAnimalesPpal)
        QtCore.QMetaObject.connectSlotsByName(MovAnimalesPpal)

    def retranslateUi(self, MovAnimalesPpal):
        _translate = QtCore.QCoreApplication.translate
        MovAnimalesPpal.setWindowTitle(_translate("MovAnimalesPpal", "Proceso Movimiento de Animales"))
        item = self.Tabla.horizontalHeaderItem(0)
        item.setText(_translate("MovAnimalesPpal", "Folio"))
        item = self.Tabla.horizontalHeaderItem(1)
        item.setText(_translate("MovAnimalesPpal", "Fecha"))
        item = self.Tabla.horizontalHeaderItem(2)
        item.setText(_translate("MovAnimalesPpal", "Cliente"))
        item = self.Tabla.horizontalHeaderItem(3)
        item.setText(_translate("MovAnimalesPpal", "Corral"))
        item = self.Tabla.horizontalHeaderItem(4)
        item.setText(_translate("MovAnimalesPpal", "Tpo.Mvto"))
        item = self.Tabla.horizontalHeaderItem(5)
        item.setText(_translate("MovAnimalesPpal", "Cant"))
        item = self.Tabla.horizontalHeaderItem(6)
        item.setText(_translate("MovAnimalesPpal", "Notas"))
        self.PBCerrar.setText(_translate("MovAnimalesPpal", "Cerrar"))
        self.PBAgregar.setText(_translate("MovAnimalesPpal", "Agregar"))
        self.groupBox_2.setTitle(_translate("MovAnimalesPpal", "Filtro"))
        self.RBotUlt100.setText(_translate("MovAnimalesPpal", "Ultimos 100"))
        self.RBotTodos.setText(_translate("MovAnimalesPpal", "Todos"))
        self.PBActualizar.setText(_translate("MovAnimalesPpal", "Actualizar Lista"))
        self.PBEditar.setText(_translate("MovAnimalesPpal", "Editar Mvto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MovAnimalesPpal = QtWidgets.QDialog()
    ui = Ui_MovAnimalesPpal()
    ui.setupUi(MovAnimalesPpal)
    MovAnimalesPpal.show()
    sys.exit(app.exec_())
