# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProductosCat.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Productos(object):
    def setupUi(self, Productos):
        Productos.setObjectName("Productos")
        Productos.resize(677, 709)
        Productos.setStyleSheet("DialogAltaAnimales{\n"
"\n"
"}\n"
"\n"
"lineEdit{  font-size: 16px;\n"
"\n"
"}")
        self.Tabla = QtWidgets.QTableWidget(Productos)
        self.Tabla.setGeometry(QtCore.QRect(10, 130, 611, 521))
        self.Tabla.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Tabla.setAlternatingRowColors(True)
        self.Tabla.setObjectName("Tabla")
        self.Tabla.setColumnCount(3)
        self.Tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(2, item)
        self.layoutWidget = QtWidgets.QWidget(Productos)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 660, 311, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PBModificar = QtWidgets.QPushButton(self.layoutWidget)
        self.PBModificar.setObjectName("PBModificar")
        self.horizontalLayout.addWidget(self.PBModificar)
        self.PBAgregar = QtWidgets.QPushButton(self.layoutWidget)
        self.PBAgregar.setObjectName("PBAgregar")
        self.horizontalLayout.addWidget(self.PBAgregar)
        self.groupBox_2 = QtWidgets.QGroupBox(Productos)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 611, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.DescripcionCampo = QtWidgets.QLineEdit(self.groupBox_2)
        self.DescripcionCampo.setGeometry(QtCore.QRect(90, 60, 271, 20))
        self.DescripcionCampo.setText("")
        self.DescripcionCampo.setObjectName("DescripcionCampo")
        self.ClaveCampo = QtWidgets.QLineEdit(self.groupBox_2)
        self.ClaveCampo.setGeometry(QtCore.QRect(53, 29, 101, 20))
        self.ClaveCampo.setText("")
        self.ClaveCampo.setObjectName("ClaveCampo")
        self.ClaveLbl = QtWidgets.QLabel(self.groupBox_2)
        self.ClaveLbl.setGeometry(QtCore.QRect(10, 29, 38, 17))
        self.ClaveLbl.setStyleSheet("QLabel {\n"
"font-size: 14px;\n"
"\n"
"}")
        self.ClaveLbl.setObjectName("ClaveLbl")
        self.NombreLbl = QtWidgets.QLabel(self.groupBox_2)
        self.NombreLbl.setGeometry(QtCore.QRect(10, 60, 75, 17))
        self.NombreLbl.setStyleSheet("QLabel {\n"
"font-size: 14px;\n"
"\n"
"}")
        self.NombreLbl.setObjectName("NombreLbl")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(380, 30, 181, 51))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.RBotAlta = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBotAlta.setFont(font)
        self.RBotAlta.setAcceptDrops(False)
        self.RBotAlta.setChecked(True)
        self.RBotAlta.setObjectName("RBotAlta")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.RBotAlta)
        self.RBotBaja = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBotBaja.setFont(font)
        self.RBotBaja.setObjectName("RBotBaja")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.RBotBaja)
        self.widget = QtWidgets.QWidget(Productos)
        self.widget.setGeometry(QtCore.QRect(330, 660, 291, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PBDetalle = QtWidgets.QPushButton(self.widget)
        self.PBDetalle.setObjectName("PBDetalle")
        self.horizontalLayout_2.addWidget(self.PBDetalle)
        self.PBCerrar = QtWidgets.QPushButton(self.widget)
        self.PBCerrar.setObjectName("PBCerrar")
        self.horizontalLayout_2.addWidget(self.PBCerrar)
        self.groupBox_2.raise_()
        self.Tabla.raise_()
        self.layoutWidget.raise_()
        self.PBDetalle.raise_()
        self.PBCerrar.raise_()

        self.retranslateUi(Productos)
        QtCore.QMetaObject.connectSlotsByName(Productos)
        Productos.setTabOrder(self.ClaveCampo, self.DescripcionCampo)
        Productos.setTabOrder(self.DescripcionCampo, self.Tabla)
        Productos.setTabOrder(self.Tabla, self.RBotAlta)
        Productos.setTabOrder(self.RBotAlta, self.PBAgregar)

    def retranslateUi(self, Productos):
        _translate = QtCore.QCoreApplication.translate
        Productos.setWindowTitle(_translate("Productos", "Catalogo de Produtos"))
        item = self.Tabla.horizontalHeaderItem(0)
        item.setText(_translate("Productos", "Clave"))
        item = self.Tabla.horizontalHeaderItem(1)
        item.setText(_translate("Productos", "Nombre"))
        item = self.Tabla.horizontalHeaderItem(2)
        item.setText(_translate("Productos", "Estatus"))
        self.PBModificar.setText(_translate("Productos", "Modificar"))
        self.PBAgregar.setText(_translate("Productos", "Agregar"))
        self.groupBox_2.setTitle(_translate("Productos", "Producto:"))
        self.ClaveLbl.setText(_translate("Productos", "Clave:"))
        self.NombreLbl.setText(_translate("Productos", "Descripcion:"))
        self.groupBox.setTitle(_translate("Productos", "Estatus Cambiar:"))
        self.RBotAlta.setText(_translate("Productos", "Activo"))
        self.RBotBaja.setText(_translate("Productos", "Baja"))
        self.PBDetalle.setText(_translate("Productos", "Ir a Recetas"))
        self.PBCerrar.setText(_translate("Productos", "Cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Productos = QtWidgets.QDialog()
    ui = Ui_Productos()
    ui.setupUi(Productos)
    Productos.show()
    sys.exit(app.exec_())
