# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RepProdsMovActual.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RepProdMovActual(object):
    def setupUi(self, RepProdMovActual):
        RepProdMovActual.setObjectName("RepProdMovActual")
        RepProdMovActual.resize(764, 638)
        self.FechaFinSel = QtWidgets.QDateEdit(RepProdMovActual)
        self.FechaFinSel.setGeometry(QtCore.QRect(480, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FechaFinSel.setFont(font)
        self.FechaFinSel.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.FechaFinSel.setCalendarPopup(True)
        self.FechaFinSel.setDate(QtCore.QDate(2021, 1, 1))
        self.FechaFinSel.setObjectName("FechaFinSel")
        self.FechaFinalLbl = QtWidgets.QLabel(RepProdMovActual)
        self.FechaFinalLbl.setGeometry(QtCore.QRect(400, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FechaFinalLbl.setFont(font)
        self.FechaFinalLbl.setObjectName("FechaFinalLbl")
        self.PBHacer = QtWidgets.QPushButton(RepProdMovActual)
        self.PBHacer.setGeometry(QtCore.QRect(10, 600, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBHacer.setFont(font)
        self.PBHacer.setObjectName("PBHacer")
        self.PBExcel = QtWidgets.QPushButton(RepProdMovActual)
        self.PBExcel.setGeometry(QtCore.QRect(130, 600, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBExcel.setFont(font)
        self.PBExcel.setObjectName("PBExcel")
        self.PBCerrar = QtWidgets.QPushButton(RepProdMovActual)
        self.PBCerrar.setGeometry(QtCore.QRect(280, 600, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBCerrar.setFont(font)
        self.PBCerrar.setObjectName("PBCerrar")
        self.Tabla = QtWidgets.QTableWidget(RepProdMovActual)
        self.Tabla.setGeometry(QtCore.QRect(10, 60, 691, 531))
        self.Tabla.setObjectName("Tabla")
        self.Tabla.setColumnCount(7)
        self.Tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(6, item)
        self.AlmacenCBox = QtWidgets.QComboBox(RepProdMovActual)
        self.AlmacenCBox.setGeometry(QtCore.QRect(90, 20, 301, 20))
        self.AlmacenCBox.setObjectName("AlmacenCBox")
        self.AlmacenLbl = QtWidgets.QLabel(RepProdMovActual)
        self.AlmacenLbl.setGeometry(QtCore.QRect(10, 20, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AlmacenLbl.setFont(font)
        self.AlmacenLbl.setObjectName("AlmacenLbl")

        self.retranslateUi(RepProdMovActual)
        QtCore.QMetaObject.connectSlotsByName(RepProdMovActual)

    def retranslateUi(self, RepProdMovActual):
        _translate = QtCore.QCoreApplication.translate
        RepProdMovActual.setWindowTitle(_translate("RepProdMovActual", "Reporte Movimiento Productos"))
        self.FechaFinalLbl.setText(_translate("RepProdMovActual", "  Fecha :"))
        self.PBHacer.setText(_translate("RepProdMovActual", "Hacer"))
        self.PBExcel.setText(_translate("RepProdMovActual", "Bajar a Excel"))
        self.PBCerrar.setText(_translate("RepProdMovActual", "Cerrar"))
        item = self.Tabla.horizontalHeaderItem(0)
        item.setText(_translate("RepProdMovActual", "Almacen"))
        item = self.Tabla.horizontalHeaderItem(1)
        item.setText(_translate("RepProdMovActual", "Producto"))
        item = self.Tabla.horizontalHeaderItem(2)
        item.setText(_translate("RepProdMovActual", "InvInic"))
        item = self.Tabla.horizontalHeaderItem(3)
        item.setText(_translate("RepProdMovActual", "Entrada"))
        item = self.Tabla.horizontalHeaderItem(4)
        item.setText(_translate("RepProdMovActual", "Salida"))
        item = self.Tabla.horizontalHeaderItem(5)
        item.setText(_translate("RepProdMovActual", "Total"))
        self.AlmacenLbl.setText(_translate("RepProdMovActual", "Almacen:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RepProdMovActual = QtWidgets.QDialog()
    ui = Ui_RepProdMovActual()
    ui.setupUi(RepProdMovActual)
    RepProdMovActual.show()
    sys.exit(app.exec_())
