# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RepVenAlmaProdPresenta.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RepVenAlmaProdPresenta(object):
    def setupUi(self, RepVenAlmaProdPresenta):
        RepVenAlmaProdPresenta.setObjectName("RepVenAlmaProdPresenta")
        RepVenAlmaProdPresenta.resize(826, 703)
        self.FechaInicSel = QtWidgets.QDateEdit(RepVenAlmaProdPresenta)
        self.FechaInicSel.setGeometry(QtCore.QRect(110, 21, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FechaInicSel.setFont(font)
        self.FechaInicSel.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.FechaInicSel.setCalendarPopup(True)
        self.FechaInicSel.setDate(QtCore.QDate(2021, 1, 1))
        self.FechaInicSel.setObjectName("FechaInicSel")
        self.FechaFinSel = QtWidgets.QDateEdit(RepVenAlmaProdPresenta)
        self.FechaFinSel.setGeometry(QtCore.QRect(340, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FechaFinSel.setFont(font)
        self.FechaFinSel.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.FechaFinSel.setCalendarPopup(True)
        self.FechaFinSel.setDate(QtCore.QDate(2021, 1, 1))
        self.FechaFinSel.setObjectName("FechaFinSel")
        self.FechaFinalLbl = QtWidgets.QLabel(RepVenAlmaProdPresenta)
        self.FechaFinalLbl.setGeometry(QtCore.QRect(240, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FechaFinalLbl.setFont(font)
        self.FechaFinalLbl.setObjectName("FechaFinalLbl")
        self.FechaIniLbl = QtWidgets.QLabel(RepVenAlmaProdPresenta)
        self.FechaIniLbl.setGeometry(QtCore.QRect(10, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FechaIniLbl.setFont(font)
        self.FechaIniLbl.setObjectName("FechaIniLbl")
        self.PBHacer = QtWidgets.QPushButton(RepVenAlmaProdPresenta)
        self.PBHacer.setGeometry(QtCore.QRect(10, 660, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBHacer.setFont(font)
        self.PBHacer.setObjectName("PBHacer")
        self.PBExcel = QtWidgets.QPushButton(RepVenAlmaProdPresenta)
        self.PBExcel.setGeometry(QtCore.QRect(130, 660, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBExcel.setFont(font)
        self.PBExcel.setObjectName("PBExcel")
        self.PBCerrar = QtWidgets.QPushButton(RepVenAlmaProdPresenta)
        self.PBCerrar.setGeometry(QtCore.QRect(280, 660, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PBCerrar.setFont(font)
        self.PBCerrar.setObjectName("PBCerrar")
        self.Tabla = QtWidgets.QTableWidget(RepVenAlmaProdPresenta)
        self.Tabla.setGeometry(QtCore.QRect(10, 100, 791, 551))
        self.Tabla.setObjectName("Tabla")
        self.Tabla.setColumnCount(6)
        self.Tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabla.setHorizontalHeaderItem(5, item)

        self.retranslateUi(RepVenAlmaProdPresenta)
        QtCore.QMetaObject.connectSlotsByName(RepVenAlmaProdPresenta)

    def retranslateUi(self, RepVenAlmaProdPresenta):
        _translate = QtCore.QCoreApplication.translate
        RepVenAlmaProdPresenta.setWindowTitle(_translate("RepVenAlmaProdPresenta", "Reporte de Salida Productos Por Almacen y Presentacion"))
        self.FechaFinalLbl.setText(_translate("RepVenAlmaProdPresenta", "Fecha Final:"))
        self.FechaIniLbl.setText(_translate("RepVenAlmaProdPresenta", "Fecha Inicial:"))
        self.PBHacer.setText(_translate("RepVenAlmaProdPresenta", "Hacer"))
        self.PBExcel.setText(_translate("RepVenAlmaProdPresenta", "Bajar a Excel"))
        self.PBCerrar.setText(_translate("RepVenAlmaProdPresenta", "Cerrar"))
        item = self.Tabla.horizontalHeaderItem(0)
        item.setText(_translate("RepVenAlmaProdPresenta", "Almacen"))
        item = self.Tabla.horizontalHeaderItem(1)
        item.setText(_translate("RepVenAlmaProdPresenta", "Material"))
        item = self.Tabla.horizontalHeaderItem(2)
        item.setText(_translate("RepVenAlmaProdPresenta", "Ensacado"))
        item = self.Tabla.horizontalHeaderItem(3)
        item.setText(_translate("RepVenAlmaProdPresenta", "Servido"))
        item = self.Tabla.horizontalHeaderItem(4)
        item.setText(_translate("RepVenAlmaProdPresenta", "Granel"))
        item = self.Tabla.horizontalHeaderItem(5)
        item.setText(_translate("RepVenAlmaProdPresenta", "SubTotal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RepVenAlmaProdPresenta = QtWidgets.QDialog()
    ui = Ui_RepVenAlmaProdPresenta()
    ui.setupUi(RepVenAlmaProdPresenta)
    RepVenAlmaProdPresenta.show()
    sys.exit(app.exec_())
