# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Unidades.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogOperadores(object):
    def setupUi(self, DialogOperadores):
        DialogOperadores.setObjectName("DialogOperadores")
        DialogOperadores.resize(307, 423)
        DialogOperadores.setStyleSheet("DialogAltaAnimales{\n"
"\n"
"}\n"
"\n"
"lineEdit{  font-size: 20px;\n"
"\n"
"}")
        self.PBCerrar = QtWidgets.QPushButton(DialogOperadores)
        self.PBCerrar.setGeometry(QtCore.QRect(160, 370, 75, 23))
        self.PBCerrar.setObjectName("PBCerrar")
        self.Tabla = QtWidgets.QTreeWidget(DialogOperadores)
        self.Tabla.setGeometry(QtCore.QRect(20, 40, 256, 251))
        self.Tabla.setAutoScrollMargin(50)
        self.Tabla.setObjectName("Tabla")
        self.Tabla.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.Tabla.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        self.label = QtWidgets.QLabel(DialogOperadores)
        self.label.setGeometry(QtCore.QRect(40, 320, 231, 16))
        self.label.setObjectName("label")

        self.retranslateUi(DialogOperadores)
        QtCore.QMetaObject.connectSlotsByName(DialogOperadores)

    def retranslateUi(self, DialogOperadores):
        _translate = QtCore.QCoreApplication.translate
        DialogOperadores.setWindowTitle(_translate("DialogOperadores", " Catalogo Unidades de Medida"))
        self.PBCerrar.setText(_translate("DialogOperadores", "Cerrar"))
        self.Tabla.headerItem().setText(0, _translate("DialogOperadores", "Descripcion"))
        self.Tabla.headerItem().setText(1, _translate("DialogOperadores", "Abreviacion"))
        self.label.setText(_translate("DialogOperadores", "Nota: Estos datos no se pueden modificar."))
